<?php

namespace CmsBundle\Repository;

/**
 * PageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SeoRepository extends \Doctrine\ORM\EntityRepository
{
}
